ProyectoCEI/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from homeApp.views import *
from newsPortal import views
from publications.views import *
from research.views import *
from membersApp.views import *
from intranetApp.views import *

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name='home'),
    path('accounts/', include("django.contrib.auth.urls")),
    path('members/', miembros, name='miembros'),
	path('infoMembers/<int:id>', infoMiembro, name='infoMembers' ),
    path('newsPortal/', views.newsPortal, name='news' ),
    path('news/<int:id>', views.newCei, name='new' ),
    path('pub/', publications, name='pub'),
    path('research/', research, name='research'),
    path('intranet/', intranet, name='intranet'),
    path('script/', script, name='script'),	
    path('data/', data, name='data'),
	path('manuals/', manual, name='manuals'),
	path('protocol/', protocol, name='protocol'),
	path('eliminarDoc/<int:id>/', eliminarDoc, name='eliminarDoc'),



]

if settings.DEBUG:
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

intranetApp/models.py
from django.db import models

# Create your models here.
class Categoria (models.Model):
    nombre = models.CharField(max_length=50)
    def __str__(self):
        return self.nombre


class Documento (models.Model):
    documento = models.FileField(upload_to='docs/', unique=True )
    categoria = models.ForeignKey(Categoria, on_delete=models.CASCADE) 
    investigador = models.CharField(max_length=50)
    proyecto =  models.CharField(max_length=50, blank=True)
    descripcion = models.CharField(max_length=150, blank=True)
    created_at = models.DateTimeField(auto_now_add=True, null=True, blank=True)
    updated = models.DateTimeField(auto_now_add=False, auto_now=True)
    
    def delete(self):
        self.documento.delete()
        super().delete()

membersApp/models.py
from django.db import models

# Create your models here.
class Members(models.Model):
    nombre = models.CharField(max_length=50)
    titulo = models.CharField(max_length=50, blank=True)
    academic_rank = models.CharField(max_length=50, blank=True)
    email = models.CharField(max_length=50, blank=True)
    g_scholar = models.CharField(max_length=100, blank=True)
    img = models.ImageField(upload_to='members/')
    descripcion = models.TextField()
    puesto = models.CharField(max_length=50, blank=True)
    universidad = models.CharField(max_length=50, blank=True)

newsPortal/models.py
from django.db import models

# Create your models here.
class Noticias (models.Model):
    encabezado = models.CharField(max_length=225)
    bajada = models.TextField(blank=True)
    fecha=models.DateField()
    portada = models.ImageField(upload_to='news/')

    def delete(self):
        self.portada.delete()
        super().delete()

class Parrafos (models.Model):
    subtitulo = models.CharField(max_length=225, blank=True)
    cuerpo = models.TextField()
    noticia = models.ForeignKey(Noticias, on_delete=models.CASCADE, related_name='parrafos')
    def __str__(self):
        return self.cuerpo
    
    
class Imgs (models.Model):
    img = models.ImageField(upload_to='news/')
    descricion = models.CharField(max_length=255)
    noticia = models.ForeignKey(Noticias, on_delete=models.CASCADE, related_name='imgs')
    def __str__(self):
        return self.descricion
    
    def delete(self):
        self.img.delete()
        super().delete()
    

class Videos (models.Model):
    video = models.FileField(upload_to='news/')
    descricion = models.CharField(max_length=255)
    noticia = models.ForeignKey(Noticias, on_delete=models.CASCADE, related_name='videos')
    def __str__(self):
        return self.descricion
    
    def delete(self):
        self.video.delete()
        super().delete()

intranetApp/forms.py
from django import forms 
from .models import Categoria, Documento

class addDoc(forms.Form):
    documento = forms.FileField()
    categoria = forms.ModelChoiceField(queryset=Categoria.objects.all())
    investigador = forms.CharField(required=False)
    proyecto = forms.CharField(required=False)
    descripcion = forms.CharField(required=False) 
    

class addDoc(forms.ModelForm):
    documento = forms.FileField()
    categoria = forms.ModelChoiceField(queryset=Categoria.objects.all())
    investigador = forms.CharField(required=False)
    proyecto = forms.CharField(required=False)
    descripcion = forms.CharField(required=False) 

    class Meta:
        model = Documento
        fields = '__all__'

membersApp/forms.py
from django import forms 
from .models import Members

class addMember(forms.ModelForm):
	class Meta:
		model = Members
		fields = ('nombre','titulo','academic_rank','email','g_scholar','img','descripcion')

homeApp/views.py
from django.shortcuts import render
from newsPortal.models import Noticias

# Create your views here.
def index(request):

    news = Noticias.objects.all()
    data = {
        'news' : news
    }

    return render(request,"homeApp/index.html", data)

intranetApp/views.py
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.decorators import login_required
from intranetApp import forms
from intranetApp.models import Documento, Categoria
from django.urls import reverse
from django.http import HttpResponseRedirect

# Create your views here.
@login_required
def intranet (request):
    form = forms.addDoc()

    docs = Documento.objects.all()

    if request.method == 'POST':
        form = forms.addDoc(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('intranet'))
        
    context = { 
        'form' : form ,
        'docs' : docs
    }

    return render(request, "intranetApp/intranet.html", context)

@login_required
def script (request):

    categoria_d = Categoria.objects.get(nombre="Scripts")
    scripts = Documento.objects.filter(categoria=categoria_d)

    data = {
        'scripts': scripts
    }

    return render(request, "intranetApp/scripts.html", data)

@login_required
def manual (request):

    categoria_d = Categoria.objects.get(nombre="Manual")
    manuals = Documento.objects.filter(categoria=categoria_d)

    data = {
        'manuals': manuals
    }

    return render(request, "intranetApp/Manuals.html", data)

@login_required
def protocol (request):

    categoria_d = Categoria.objects.get(nombre="Protocolo")
    protocolos = Documento.objects.filter(categoria=categoria_d)

    data = {
        'protocolos': protocolos
    }

    return render(request, "intranetApp/protocol.html", data)

@login_required
def data (request):

    categoria_d = Categoria.objects.get(nombre="Datos")
    datos = Documento.objects.filter(categoria=categoria_d)

    data = {
        'datos': datos
    }

    return render(request, "intranetApp/data.html", data)


@login_required
def eliminarDoc(request, id):
    doc = get_object_or_404(Documento, id=id)
    doc.delete()
    return HttpResponseRedirect(reverse('intranet'))

membersApp/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse
from membersApp import forms
from membersApp.models import Members

# Create your views here.

def miembros(request):

    members = Members.objects.all()
    data = {
        'members' : members
    }

    return render(request,"members/members.html", data)

def addMiembro(request):
    form = forms.addMember()

    if request.method == 'POST':
        form = forms.addMember(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('addMember'))


    context = {'form': form }

    return render(request, "members/addMembers.html", context)

def infoMiembro(request, id):

    member = Members.objects.get(id = id)
    members = Members.objects.all()

    data = {
        'member' : member,
        'members' : members
    }

    return render(request,"members/infoMember.html", data)

newsPortal/views.py
from django.shortcuts import render
from newsPortal.models import Noticias

# Create your views here.
def newsPortal(request):
    news = Noticias.objects.all()
    data = {
        'news' : news
    }

    return render(request,"news/news.html", data) 

def newCei (request, id):
    new = Noticias.objects.get (id = id)
    data = {
        'new' : new
    }

    return render(request, "news/new.html", data)

publications/views.py
from django.shortcuts import render

# Create your views here.
def publications(request):
    return render(request,"publications/publications.html")

research/views.py
from django.shortcuts import render

# Create your views here.
def research (request):
    return render(request, "research/research.html")

templates/base.html
{% load static %}
<!doctype html>
<html lang="es">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Centre of Integrative Ecology - {% block title %}{% endblock %}</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Noto+Sans&display=swap" rel="stylesheet">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Montserrat&display=swap" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    {% block extra_css %}{% endblock %}
  </head>
  <body>
    <!-- Navbar -->
    <div class="container-fluid text-center" id="navbarContainer">
      <div class="row justify-content-center">
        <div class="col-2 mt-3" style="padding: 0%;">
          <a href="{% url 'home' %}"><img src="{% static 'img/logo.png' %}" alt="logo" width="150px"></a>
        </div>
      </div>
      <div class="row justify-content-center">
        <div class="col mt-3">
          <nav class="nav navbar-expand-lg">
            <button class="navbar-toggler custom-custom-toggler custom-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <i class="bi bi-list icon-white"></i>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mx-auto mb-2 mb-lg-0 justify-content-center">
                  <li class="nav-item custom-nav-item me-5">
                    <a class="nav-link" href="{% url 'home' %}">Home</a>
                  </li>
                  <li class="nav-item custom-nav-item me-5">
                    <a class="nav-link" href="{% url 'research' %}">Research</a>
                  </li>
                  <li class="nav-item custom-nav-item me-5">
                    <a class="nav-link" href="{% url 'miembros' %}">Members</a>
                  </li>
                  <li class="nav-item custom-nav-item me-5">
                    <a class="nav-link" href="{% url 'pub' %}">Publications</a>
                  </li>
                  <li class="nav-item custom-nav-item me-5">
                    <a class="nav-link" href="{% url 'news' %}">News</a>
                  </li>
                </ul>
            </div>
          </nav>
        </div>
      </div>
    </div>

    {% block content %}{% endblock %}

    <!-- Footer -->
    <div class="container-fluid text-center px-5 py-5" id="footer">
      <div class="row">
        <div class="col">
          <div class="row">
            <img src="{% static 'img/logo.png' %}" alt="logo del cei" style="width: 10rem;" >
          </div>
          <div class="row">
            <img src="{% static 'img/logoutal.png' %}" alt="logo de utal" style="width: 10rem;" class="my-5">
          </div>
        </div>
        <div class="col">
          <div class="row sec-footer">
            Navegation
          </div>
          <ul class="list-footer">
            <li class="mb-2">
              <a href="{% url 'home' %}" class="item-footer">Home</a>
            </li>
            <li class="mb-2">
              <a href="{% url 'research' %}" class="item-footer">Research</a>
            </li>
            <li class="mb-2">
              <a href="{% url 'miembros' %}" class="item-footer">Members</a>
            </li>
            <li class="mb-2">
              <a href="{% url 'pub' %}" class="item-footer">Publications</a>
            </li>
            <li class="mb-2">
              <a href="{% url 'news' %}" class="item-footer">News</a>
            </li>
          </ul>
        </div>
        <div class="col">
          <div class="row sec-footer">
            Contact
          </div>
          <ul class="list-footer">
            <li class="mb-2 item-footer">
              contact@cei.cl
            </li>
            <li class="mb-2 item-footer">
              Address: Universidad de Talca ¿?
            </li>
          </ul>
        </div>
        <div class="col">
          <div class="row sec-footer">
            social networks
          </div>
          <ul class="list-footer">
            <li class="mb-2 icon-footer">
              <a href="https://www.instagram.com/" class="list-footer item-footer"> <i class="bi bi-instagram"></i> </a>
            </li>
            <li class="mb-2 icon-footer">
              <a href="https://www.tiktok.com/login?lang=es&redirect_url=https%3A%2F%2Fwww.tiktok.com%2Fupload%3Flang%3Des" class="list-footer item-footer"> <i class="bi bi-tiktok"></i> </a>
            </li>
            <li class="mb-2 icon-footer">
              <a href="https://twitter.com/i/flow/login" class="list-footer item-footer"> <i class="bi bi-twitter-x"></i> </a>
            </li>
          </ul>
        </div>
      </div>
      <div class="row align-items-end justify-content-end">
        <div class="col-2">
          <a href="{% url 'login' %}" target="_blank" class="item-footer"> Private workspace </a>
        </div>
      </div>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
    {% block extra_js %}{% endblock %}
  </body>
</html>

templates/homeApp/index.html
<!doctype html>

    {% load static %}

<html lang="es">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Centre of Integrative Ecology - Home</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Noto+Sans&display=swap" rel="stylesheet">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Montserrat&display=swap" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
    <link rel="stylesheet" href="{% static 'css/home.css' %}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css" integrity="sha512-c42qTSw/wPZ3/5LBzD+Bw5f7bSF2oxou6wEb+I/lqeaKV5FDIfMvvRp772y4jcJLKuGUOpbJMdg/BTl50fJYAw==" crossorigin="anonymous" referrerpolicy="no-referrer" />

    
  </head>

  <body>

    <!--Header-->
    <div class="container-fluid text-center" id="headerHome">



      <!--Navbar-->
      <div class="row align-items-top justify-content-between">

        <div class="col-2 mt-4">
            
          <img src="{% static 'img/logosolo.png' %}" alt="logo" width="130px">              

        </div>

        <div class="col-6 mt-5">

          {% include 'includes/navbar.html' with active='home' %}

        </div>
          
      </div>

      <!--Titulo-->
      <div class="row justify-content-start" >

          <div class="col-7" id="tituloHome">
              <h2 class="ms-5" style="font-weight: bold;">
                  Centre for Integrative Ecology
              </h2>
              <h4 class="ms-5" >
                Understanding natural processes requires integrating diverse knowledge from various fields, aiming to <b>study ecological phenomena through a multiscale approach.</b>
              </h4>
          </div>            

      </div>




    </div>


    <!--About section-->
    <div class="container my-5" id="aboutHome">
      <div class="row justify-content-center">
        <div class="col-md-8 text-center">
          <h3 class="mb-3" style="color:#3A7DA4; font-weight: bold;">
            About us
          </h3>
          <p>
            The Centre for Integrative Ecology (CEI) brings together researchers
            from diverse disciplines to advance ecological understanding across
            spatial and temporal scales.
          </p>
          <a href="{% url 'research' %}" class="btn btn-primary mt-3" style="background-color:#3A7DA4; border-color:#3A7DA4;">
            Learn more about our work
          </a>
        </div>
      </div>
    </div>

    <!--Lines of research-->
    <div class="row align-items-center justify-content-evenly mx-5 my-5">

      <h5 class="col " style="font-weight: bold;">
        Research lines:
      </h5>

      <a href="{% url 'research' %}" style="background-color: #025E73;" class="ovalos py-3 col"><i class="bi bi-stars"></i> Astroecology </a>
      <a href="{% url 'research' %}" style="background-color: #B2CF53;" class="ovalos py-3 col"><i class="bi bi-bug-fill"></i> Microbial Ecology </a>
      <a href="{% url 'research' %}" style="background-color: #D97823;" class="ovalos py-3 col"><i class="bi bi-feather2"></i> Plant Ecology </a>
      <a href="{% url 'research' %}" style="background-color: #525507;" class="ovalos py-3 col"><i class="bi bi-people-fill"></i> Socioecology </a>

    </div>
    <a href="{% url 'news' %}" style="background-color:#3A7DA4; border-color:#3A7DA4; "  class="col-2 align-self-center btn btn-primary mt-3 mx-5"> News portal... </a>
  </div>
  <div class="row justify-content-evenly gx-5">
    {% for new in news|slice:":4" %}
    <div class="card my-3" style="width: 17rem; ">
      <img src="{% static 'img/new1.webp' %}" alt="img" class="card-img-top">
      <div class="card-header text-body-secondary fw-lighter fst-italic"> {{new.fecha}} </div>
      <div class="card-body" style="text-align: left;">
        <h5 class="card-title"> {{new.encabezado}} </h5>
        <hr>
        <p class="card-text"> {{new.subtitulo}} </p>
        <a href="/news/{{new.id}}" class="card-link">Read more...</a>
      </div>
    {% endfor %}
  </div>
</div>
{% endblock %}

templates/includes/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark">
  <div class="container">
    <button class="navbar-toggler custom-custom-toggler custom-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <i class="bi bi-list icon-white"></i>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mx-auto mb-2 mb-lg-0 justify-content-center">
          <li class="nav-item custom-nav-item me-5">
            <a class="nav-link {% if active == 'home' %}active{% endif %}" href="{% url 'home' %}">Home</a>
          </li>
          <li class="nav-item custom-nav-item me-5">
            <a class="nav-link {% if active == 'research' %}active{% endif %}" href="{% url 'research' %}">Research</a>
          </li>
          <li class="nav-item custom-nav-item me-5">
            <a class="nav-link {% if active == 'members' %}active{% endif %}" href="{% url 'miembros' %}">Members</a>
          </li>
          <li class="nav-item custom-nav-item me-5">
            <a class="nav-link {% if active == 'publications' %}active{% endif %}" href="{% url 'pub' %}">Publications</a>
          </li>
          <li class="nav-item custom-nav-item me-5">
            <a class="nav-link {% if active == 'news' %}active{% endif %}" href="{% url 'news' %}">News</a>
          </li>
        </ul>
    </div>
  </div>
</nav>
<script>
  document.addEventListener('scroll', function () {
    const nav = document.querySelector('.navbar');
    if (window.scrollY > 50) {
      nav.classList.add('scrolled');
    } else {
      nav.classList.remove('scrolled');
    }
  });
</script>

templates/intranetApp/Manuals.html
{% extends "./intranetBase.html" %} 

{% block contenido %}
<div class="container content-center mt-5" >

    {% if manuals %}

            <table class="table " id="tablaManuals" >

                <thead>
                    <tr>
                        <th>Documento</th>
                        <th>Descripción</th>
                        <th>Fecha de Creacion</th>
                        <th>Eliminar</th>

                    </tr>
                </thead> 

                <tbody>
 
                    {% for manual in manuals %}
                        <tr>
                            <td> <a href="{{manual.documento.url}}" target="_blank">{{manual.documento}}</a> </td>
                            <td>{{manual.descripcion}}</td>
                            <td>{{manual.created_at}}</td>
                            
                            <td>
                                <a href="{% url 'eliminarManual' manual.id %}" class="btn btn-danger"  ><i class="bi bi-trash3"></i></a>
                            </td>
                        </tr>
                    {% endfor %}

                    <div class="container text-center"> 
                        <a href="{% url 'addManual' %}" class="btn btn-success" >
                            <span> Nuevos Manuales </span>
                        </a>
                    </div>

                </tbody>

            </table>

        {% else %}

            <div class="alert container alert-danger text-center display-4 my-3">
                No Hay Manuales Registrados
            </div>

            <div class="container text-center"> 
                <a href="{% url 'addManual' %}" class="btn btn-success" >
                    <span> Nuevos Manuales </span>
                </a>
            </div>


        {% endif %}

    

</div>

<!-- Eliminar Modal-->
<div class="modal fade" id="eliminarModal" tabindex="-1" role="dialog" aria-labelledby="ModalLabel"
aria-hidden="true">
<div class="modal-dialog" role="document">
    <div class="modal-content">
        <div class="modal-header">
            <h5 class="modal-title" id="ModalLabel">¿Esta seguro que desea elimiar el documento?</h5>
            <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">×</span>
            </button>
        </div>
        <div class="modal-body">"If you click 'sure', all records of the document will be lost."</div>
        <div class="modal-footer">
            <button class="btn btn-success" type="button" data-dismiss="modal">Cancel</button>
            <a class="btn btn-danger" href="#">Sure</a>
        </div> 
    </div>
</div>
</div>



{% endblock %} 

templates/intranetApp/addScript.html
{% extends "./intranetBase.html" %} 

{% block contenido %}

<div class="container content-center mt-5" >

    <form method="post" enctype="multipart/form-data">

        {% csrf_token %}
        {{ form.as_p }}

        <button class="btn btn-success" type="submit">
            Submit
        </button>

    </form>

</div>


{% endblock %} 

templates/intranetApp/data.html
{% extends "./intranetBase.html" %} 

{% block contenido %}
<div class="container content-center mt-5" >

    {% if datos %}

        <table class="table" id="tablaDatas" >

            <thead>
                <tr>
                    <th>Documento</th>
                    <th>Investigador</th>
                    <th>Proyecto</th>
                    <th>Descripción</th>
                    <th>Fecha de Creacion</th>
                    <th>Eliminar</th>

                </tr>
            </thead> 

            <tbody>

                {% for dato in datos %}
                    <tr>
                        <td> <a href="{{dato.documento.url}}" target="_blank">{{dato.documento}}</a> </td>
                        <td>{{dato.investigador}}</td>
                        <td>{{dato.proyecto}}</td>
                        <td>{{dato.descripcion}}</td>
                        <td>{{dato.created_at}}</td>
                        
                        <td>
                            <a href="{% url 'eliminarDoc' dato.id %}" class="btn btn-danger"  ><i class="bi bi-trash3"></i></a>
                        </td>
                    </tr>
                {% endfor %}

            </tbody>

        </table>

        <div class="container mt-5">
            <a href="{% url 'intranet' %}" class="btn btn-success"> Subir Nuevo Documento </a>
        </div>

        {% else %}

            <div class="alert container alert-danger text-center display-4 my-3">
                No Hay Datos Registrados
            </div>


        {% endif %}

    

</div>

<!-- Eliminar Modal-->
<div class="modal fade" id="eliminarModal" tabindex="-1" role="dialog" aria-labelledby="ModalLabel"
aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="ModalLabel">¿Esta seguro que desea elimiar el documento?</h5>
                <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">×</span>
                </button>
            </div>
            <div class="modal-body">"If you click 'sure', all records of the document will be lost."</div>
            <div class="modal-footer">
                <button class="btn btn-success" type="button" data-dismiss="modal">Cancel</button>
                <a class="btn btn-danger" href="#">Sure</a>
            </div> 
        </div>
    </div>
</div>



{% endblock %} 

templates/intranetApp/intranet.html
{% extends "./intranetBase.html" %} 

{% block contenido %}

<div class="container p-5">

    <div class="row justify-content-center">
        <div class="col-6 mb-5 text-center">

            <form method="post" enctype="multipart/form-data">

                {% csrf_token %}
                <div class="container-fluid  mb-3">
                    <input type="file" class="upload-box" name="documento" required id="id_documento" >
                    
                </div>

                <div>
                    
                    <div class="row align-items-center mb-3">
                        <div class="col-3"><label for="id_categoria" class="col-form-label">Categoria:</label></div>
                        <div class="col-6">
                            <select class="form-select"  name="categoria" required id="id_categoria">
                                <option value="" selected>---------</option>
                        
                                <option value="10">Scripts</option>
                        
                                <option value="20">Manual</option>
                            
                                <option value="30">Protocolo</option>
                            
                                <option value="40">Datos</option>
                        
                            </select> 
                        </div>
                        
                        
                    </div>  
                      
                    <div class="row align-items-center mb-3">
                        <div class="col-3"><label for="id_investigador" class="col-form-label">Investigador:</label></div>
                        <div class="col-6"><input type="text" name="investigador" required id="id_investigador" class="form-control" > </div>
                        
                    </div>
                    
                    <div class="row align-items-center mb-3">
                        <div class="col-3"><label for="id_proyecto" class="col-form-label">Proyecto:</label></div>
                        <div class="col-6"><input type="text" name="proyecto" required id="id_proyecto" class="form-control" ></div>
                    </div>
                    
                    <div class="row align-items-center mb-3">
                        <div class="col-3"><label for="id_descripcion" class="col-form-label">Descripcion:</label></div>
                        <div class="col-6"><input type="text" name="descripcion" required id="id_descripcion" class="form-control" ></div>
                            
                    </div>
    
                </div>

                <div class="container-fluid mt-5">
                    <input class="btn btn-success w-50" value='Subir Archivo' type="submit">
                </div>

            </form>            
            
        </div>
        <div class="col-12 mt-5">

            {% if docs %}

                <table class="table" id="tablaDocs" >

                    <thead>
                        <tr>
                            <th>Documento</th>
                            <th>Categoria</th>
                            <th>Investigador</th>
                            <th>Proyecto</th>
                            <th>Descripción</th>
                            <th>Fecha de Creacion</th>
                            

                        </tr>
                    </thead> 

                    <tbody>
    
                        {% for doc in docs %}
                            <tr>
                                <td> <a href="{{doc.documento.url}}" target="_blank">{{doc.documento}}</a> </td>
                                <td>{{doc.categoria}}</td>
                                <td>{{doc.investigador}}</td>
                                <td>{{doc.proyecto}}</td>
                                <td>{{doc.descripcion}}</td>
                                <td>{{doc.created_at}}</td>
                                
                            </tr>
                        {% endfor %}

                    </tbody>

                </table>
              
            {% endif %}

        </div>
    </div>


</div>



{% endblock %} 